services:
  mongo:
    image: mongo:latest
    container_name: hastane-mongo
    # Host'ta 27018'e map'liyoruz, sadece istersen kontrol/test amaçlı
    ports:
      - "27018:27017"

  backend:
    container_name: hastane-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      # DİKKAT: Mongo'ya "mongo" servisi üzerinden, 27017 portundan bağlanacağız.
      # 'hastane_sistemi' de senin veritabanının ismi.
      MONGO_URI: "mongodb://mongo:27017/hastane_sistemi"

  frontend:
    container_name: hastane-frontend
    build:
      context: ./admin-panel
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
