services:
  mongo:
    image: mongo:latest
    container_name: hastane-mongo
    # Bu port mapping'i istersen koymayabilirsin. Koyunca host tarafında 27018 -> container:27017
    ports:
      - "27018:27017"

  backend:
    container_name: hastane-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      # Mongo'ya container ismi "mongo" üzerinden bağlanacağız
      MONGO_URI: "mongodb://mongo:27017/hastane_sistemi"

  frontend:
    container_name: hastane-frontend
    build:
      context: ./admin-panel
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
